name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug", "triage"]
assignees:
  - laymain
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: mod
    attributes:
      label: Mod
      description: Which mod this bug report is for?
      options:
        - SkipVideos
        - ParagonMod
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output found in ShipOfFools\BepInEx\LogOutput.log. This will be automatically formatted into code, so no need for backticks.
      render: shell